### ISSUE TITLE
precompiled releases ...

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#1]
hi dear ...
amazing work :]

but seems that the precompiled packages like **[this](https://github.com/eidosmontreal/unreal-vdb/releases/download/v0.2.0/SparseVolumetrics_UE_Preview_0.2.0.zip)** does not have any **.dll** files!!

**Comment by thilamb** [comment]
You're right, it is strange. The UE scripts have apparently changed, I will look into this.

Also stange, I've been able to use the plugin on a clean PC and clean UE install, even without the dlls (took a couple retrys).

Let me know if you can also use it

**Comment by davoodkharmanzar** [comment]
![Untitled-1](https://user-images.githubusercontent.com/10723167/158247773-7f02e334-adb9-4c54-a8ac-7e491f1542d9.png)

**Comment by thilamb** [comment]
Say yes. That’s normal.

**Comment by davoodkharmanzar** [comment]
but ...
i can't rebuild it :[

**Comment by davoodkharmanzar** [comment]
and it would be great if deploy precompiled package without **intermediate** and **source** folders :]

**Comment by thilamb** [comment]
I've uploaded a [new zip file](https://github.com/eidosmontreal/unreal-vdb/releases/download/v0.2.0/SparseVolumetrics_UE_Preview_0.2.0.zip) containing the binaries. Hopefully it will work this time.

Once you click Yes ("would you like to rebuild them now), it will either prompt a new Unreal window showing "Starting build", or it will silently compile in your background (you can check your windows processes), take a minute or two and then launch Unreal with the plugin.

Let me know

ps: I will work on striping the package later
