### ISSUE TITLE
Module "VolumeSequencer" cannot be loaded, so the plugin "SparseVolumetrics load failure.

### ISSUE THREAD

**Issue by Edinburhg1** [eidosmontreal/unreal-vdb#10]
I loaded the VDB plug-in in my project and restarted UE5.  The VolumeSequencer can not be loaded when the compilation is complete.  I used Precompiled_UE5.0_0.3.0  and 5.0_0.3.1 still had the same problem

LoginId:247843264071c73223b0d1988864fd2c
EpicAccountId:dfff463210f84ef89d83c23831ffe487

Assertion failed: Object->HasAnyFlags( RF_BeginDestroyed ) && !Object->HasAnyFlags( RF_FinishDestroyed ) [File:D:\build\++UE5\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\GarbageCollection.cpp] [Line: 1801]

UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor_CoreUObject
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by thilamb** [comment]
Sadly, this error message is not giving any pertinent information.

Is this still happening ? You could try having the plugin in your project/plugins OR you engine/plugins folder. See if any one of these work better.

**Comment by Edinburhg1** [comment]
It works now
The installation path of UE5 must be in "C: Program Files Epic Games ue_5.0", otherwise the plugin will not load successfully  

Thank you.
