### ISSUE TITLE
Consistent Crashes (UE 5.0.1)

### ISSUE THREAD

**Issue by dangerstudios** [eidosmontreal/unreal-vdb#11]
Getting consistent crashes when trying to switch from the default unlit to default lit shader atm (latest release)
![image](https://user-images.githubusercontent.com/63320852/166627306-eacfa0de-f1b9-4707-89f8-80145ef5e3bb.png)

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\D3D12RHI\Private\D3D12Util.cpp] [Line: 859] hr failed at D:\build\++UE5\Sync\Engine\Source\Runtime\D3D12RHI\Private\D3D12Resources.cpp:629 with error DXGI_ERROR_DEVICE_REMOVED with Reason: DXGI_ERROR_DEVICE_HUNG

UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_RHICore
UnrealEditor_RHICore
UnrealEditor_RHICore
UnrealEditor_D3D12RHI
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll

**Comment by thilamb** [comment]
I've also noticed that crash at some point. These materials were made with the preview release of Unreal. They are all due for an update.
Coud you try with this asset please ? 
[M_Vdb_DefaultLit.zip](https://github.com/eidosmontreal/unreal-vdb/files/8626722/M_Vdb_DefaultLit.zip)
 
 Just overwrite the same file in your Plugin/Content folder.

**Comment by dangerstudios** [comment]
awesome thanks for that! it still seems to further down the sequence :(. I'll keep trying to debug

**Comment by thilamb** [comment]
Ok sorry about that.

I’m working on the next « major » release right now, it should take another
two weeks I think but I’ll go through all assets by then, hopefully
everything will be more robust by then.

Will let tou know when it's done

Thanks

**Comment by dangerstudios** [comment]
awesome!!

yeah so have been debugging, changed the tdlr settings and drivers etc. still persistent when the vdb seq starts to get larger in scale(and in mb). this only happens with the default lit material. so maybe there is some hungry raymarching going on? I dunno.

I'm going to try and reduce the size of the vdb seq in houdini, atm I have stripped everything except density. in general it's not a large sim, here is the vdb seq for ref:
https://drive.google.com/open?id=1pSAs3_nMw3x143Lj8lb24X7-8j9fjtvQ&authuser=mark%40danger.studio&usp=drive_fs



LoginId:c2fd780c4a10a2fe168c7f8becc0df07
EpicAccountId:98a457c1d7254651a59b5d190becfce2

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\D3D12RHI\Private\D3D12Util.cpp] [Line: 859] hr failed at D:\build\++UE5\Sync\Engine\Source\Runtime\D3D12RHI\Private\D3D12Resources.cpp:629 with error DXGI_ERROR_DEVICE_REMOVED with Reason: DXGI_ERROR_DEVICE_HUNG

UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_D3D12RHI
UnrealEditor_RHICore
UnrealEditor_RHICore
UnrealEditor_RHICore
UnrealEditor_D3D12RHI
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll

**Comment by thilamb** [comment]
This typically looks like too many raymarching steps taht your GPU doesn’t
support and ends up crashing.

What GPU are you using?

There’s a « step size » option in the VDB actor, maybe try pushing this to
higher values to avoid crashing while I try looking for a better/simpler
raymarching process with the new plugin refactor.

**Comment by dangerstudios** [comment]
oh sorry: windows 10, 3090 rtx, unreal 5x and tried on multiple computers, something to do with that shader potentially?

**Comment by dangerstudios** [comment]
also steps are up to 10

**Comment by dangerstudios** [comment]
I think it's a raymarching vram issue? but no idea really

**Comment by thilamb** [comment]
I will close this issue as there is a new much more powerful raymarcher with the 0.4 version.
Let me know if it works for you as well.
