### ISSUE TITLE
VDB Sequence seems to be skipping or remapping frames?

### ISSUE THREAD

**Issue by dangerstudios** [eidosmontreal/unreal-vdb#12]
4 frames ahead @ frame 19 and 14 frames ahead @ frame 60
![image](https://user-images.githubusercontent.com/63320852/166627705-82e14cbf-01b7-48f2-b435-4f0bb306c642.png)
![image](https://user-images.githubusercontent.com/63320852/166627827-34cc3e23-c0d6-4528-8810-47e874ce5edd.png)

**Comment by thilamb** [comment]
I've forwarded this to my colleague Sami who implemented the Sequencer support. 

We need more time and exploration to understand what is happening. Will let you know when we have an update, but it may take a while.

**Comment by dangerstudios** [comment]
ok no worries, still super awesome!

**Comment by vgrant** [comment]
I ran into this issue last night as well. I was debugging it this morning before I found this issue and noticed if I set the Sequencer FPS  to 29.97 it will not skip any frames. Hopefully that's helpful info.

**Comment by thilamb** [comment]
I've taken the time to look at it  and study it, and this is just the "normal" behavior. Depending on your chosen FPS in the sequencer, the frames will adapt to reflect the FPS.
Like vgrant says, the "default" value should be 30FPS, or 29.97FPS to be even better.

Hope this helps. I will close this issue as it is not an issue in the end.
