### ISSUE TITLE
Remapping

### ISSUE THREAD

**Issue by dangerstudios** [eidosmontreal/unreal-vdb#15]
is it possible to add some remapping option in the shader? for example to artistically change the look of the volume via the material

**Comment by thilamb** [comment]
Not sure what you  by remapping,

But you can change the color/scattering with albedo, change the extinction
which acts as a mutliplier so you could for example animate a noise
erosion, play with emissive or AO (simple multiplier)

You can even modify the raymarching loop with a CustomHlsl node but it’s
way more advanced. There is an example material in the plugin to give you a
starting point.

**Comment by thilamb** [comment]
I'll close this issue but feel free to poke me if you have other (un)related questions !

**Comment by dangerstudios** [comment]
ah sorry, meant to reply; so in the "shader" if there was an option(s) to mess with the vdb channels. for example: for density, a visual ramp to tweak the values based on the evaluated input range?

**Comment by thilamb** [comment]
That's easy to do right now by customizing the "extinction" parameter in the material. Just plug in a few nodes to modify it, and the result will be multiplied with the vdb density.

Here is an example of density tweaking the Stanford bunny

![2022-05-10 09_51_21-Window](https://user-images.githubusercontent.com/7030046/167669063-eede8dc2-73a5-4e31-ad8c-57b2753d4ddf.png)

**Comment by dangerstudios** [comment]
ok awesome, cheers!
