### ISSUE TITLE
Is there anywhere to Implement a Mesh Draw Without define own vertex Factory?

### ISSUE THREAD

**Issue by ActiveXSturcture** [eidosmontreal/unreal-vdb#17]
Because my work is same to this Project to bring the vdb file to Unreal Engine,but my implement is convert the vdb file to VolumeTexture and use it in material editor.But when i read your Project Source code I found it is possible to add Pass to Unreal without change the source code.The vertex factory you achieved is almost the copy of LocalVertexFactory.ush except the tranform matrix you define.So i wondering is there any way without write own vertex factory file to implement the Mesh Draw like you did?

**Comment by thilamb** [comment]
Not that I know of, and not at the time I was writing the plugin.

Nowadays, [Unreal geometry scripts](https://docs.unrealengine.com/5.0/en-US/geometry-script-users-guide/) tools look ideal for this kind of use, I'm pretty sure it would / could work although I haven't tried it so far.

Using and customizing Niagara Fluids might also be a good way to try, it is much more customizable than anything else in the engine. But again, I haven't tried it so far so no guarantees.

If you do find an elegant solution, please let me know !
