### ISSUE TITLE
Enabling the plugin causes packaging for windows to fail with an error. 

### ISSUE THREAD

**Issue by barrydineen** [eidosmontreal/unreal-vdb#18]
I started a new UE project and enabled the plugin and the package fails with the following error:

UATHelper: Packaging (Windows): ERROR: Expecting to find a type to be declared in a module rules named 'VolumeSequencer' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
PackagingResults: Error: Expecting to find a type to be declared in a module rules named 'VolumeSequencer' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.

**Comment by thilamb** [comment]
Hello,

I need more context for this error please.

Are you compiling from source ? Or are you using the precompiled Release packages ? Which one ?

What is your Unreal version ? 

What is your GPU and basic computer info ?

Thanks

**Comment by barrydineen** [comment]
Thanks for the quick response. 

Precompiled Release package UE5.0_0.3.2

I put it here C:\Program Files\Epic Games\UE_5.0\Engine\Plugins\SparseVolumetrics

UE 5.0.1

RTX 3090 - Ryzen 9 5950x 16-Core processor - 64 GB Ram.

This plugin is a game-changer. Ty for creating.

Cheers,

**Comment by thilamb** [comment]
Thanks for the reply and kind words !

UE5.0.1 has some changes that make the previous versions crash.

Use the correct plugin 0.3.3 instead please:
https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.3.3

Let me know !

**Comment by barrydineen** [comment]
Same error with 0.3.3 - full log attached.
[VDB_Plugin.log](https://github.com/eidosmontreal/unreal-vdb/files/8673894/VDB_Plugin.log)

I tried a development build and a shipping build with the same result.

**Comment by MaximeDup** [comment]
Hello @barrydineen, can you try placing the plugin locally in your "UE_Project/Plugins/" folder?
Had no problem packaging and running a demo in development mode that way.

**Comment by thilamb** [comment]
I was about to say the same thing. I've never seen these errors, it's probably because you don't have the plugin in the right folder. Try Maxime's suggestion: "UE_Project/Plugins/"

Make sure you've read [these instructions](https://github.com/eidosmontreal/unreal-vdb#installation) please.

If you are compiling your project, you might as well clone the repo (and not use the prepackaged release version). Make sure you are up to date.

**Comment by barrydineen** [comment]
Thanks @MaximeDup and @thilamb. I'm getting the Cook failed error when I place the plugin locally in my project but based on the fact that @MaximeDup is able to package I think we can assume that this is a me issue. I'll try compiling from the repo clone. Appreciate the effort and time and feel free to close this out. Cheers.

**Comment by thilamb** [comment]
No worries, good luck, hope it's going to work on your side.
