### ISSUE TITLE
UE5.0.1 No materials on the VDB files!

### ISSUE THREAD

**Issue by merecesarchviz** [eidosmontreal/unreal-vdb#19]
I install the last version you add but when i import any vdb into unreal and drag it to the viewport the object is transparent don't have materials on it! I try to change for other preset but all the same transparent nothing appear in the viewport! how i can fix it?

**Comment by thilamb** [comment]
I'm guessing you need to wait a while for Unreal shaders to compile. You should have a progress bar in the lower right corner.

**Comment by merecesarchviz** [comment]
Yes, it was the problem! all working nice now, thank you for the plung in have a huge potencial. best

**Comment by thilamb** [comment]
Thanks ! Have fun with it, and feel free to share your results.
