### ISSUE TITLE
Postprocess Clipping custom code??

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#2]
hi and thanks for this amazing work ...

i have an outline postprocess material that i want to clip [erase] that outlines of behind the volume ...
so ... does exists any custom code to use it on postprocess material to do that? [for **VDBActor** and **VDBReasearchActor**]
thanks.

![HighresScreenshot00001](https://user-images.githubusercontent.com/10723167/158765378-152ff9be-a4e1-4f35-8b7d-196aa4288f07.png)

**Comment by thilamb** [comment]
Transparent / translucent object don't write in depth (including VDB objects), so I don't think you can achieve this.

Maybe try using a custom Mask with Unreal's custom depth stencil (unrelated to the plugin) ?

**Comment by davoodkharmanzar** [comment]
too bad :[
