### ISSUE TITLE
scene turns black when imported vdb in unreal engine 5

### ISSUE THREAD

**Issue by qwame01** [eidosmontreal/unreal-vdb#21]
scene turns black when imported vdb in unreal engine 5

**Comment by thilamb** [comment]
Thanks, I've already fixed this issue but haven't uploaded it yet. 

In the meantime, you can fix the issue by using the "Epic" quality setting in the "Effects" category.

This is a screenshot **showing the issue**. Set "Effects" back to Epic and you should be fine.
![2022-05-31 08_44_38-](https://user-images.githubusercontent.com/7030046/172217859-b28d81ef-c9b8-4785-a85b-a51ec50eecb6.png)

**Comment by thilamb** [comment]
This issue is now fixed with the 0.4.1 version.
https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.4.1

https://github.com/eidosmontreal/unreal-vdb/commit/4436e5015ea54475bb4f1ee404d739d55c424e69#r75969609

Thanks for reporting it !
