### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by thomasgold123** [eidosmontreal/unreal-vdb#23]
Hello, I have added the VDB into a scene in unreal 5 and it works with the directional light but because this scene is an interior shot and has been lit using RectLights it doesn't seem to be lit using these. Can the VDB only be lit using a directional light? 

Thank you, 

Thomas

**Comment by thilamb** [comment]
Sadly, yes. We only support the directional light for now. 

Supporting all lights would require way more work, and reduce performances.

**Comment by thomasgold123** [comment]
thank you for your fast reply! ahh okay, that's no problem.
