### ISSUE TITLE
Pathtracing issue

### ISSUE THREAD

**Issue by guitargodmiles** [eidosmontreal/unreal-vdb#24]
Hello,  when I change the view mode to path tracing my vdb disappears.  I have direct X12 and path tracing enabled in project settings.  Am I doing something else wrong?

**Comment by thilamb** [comment]
Only VdbPrincipledActors are compatible with the pathtracer.
Cf documentation here
https://github.com/eidosmontreal/unreal-vdb#the-hardcoded-way

The other VdbActors will disappear when you activate pathtracing.

I also recommend checking the provided example maps for help.

Thanks

**Comment by guitargodmiles** [comment]
Thanks for the prompt response and link to the documentation.  I understand now!
