### ISSUE TITLE
Support for other lights in Principled Actor Mode

### ISSUE THREAD

**Issue by musamaster** [eidosmontreal/unreal-vdb#25]
Is there a way to use other lights than directional and sky to light up the volumes? We've downloaded the cloud lighting toolset and that works with the traditional volumes but we couldn't find a way to light up the principled actors

**Comment by thilamb** [comment]
Hello, sadly the vdb actors are using a custom rendering path and lighting and shadowing information is not available from a plugin at this time. We've asked Epic to give us access to it but it may take a while.
