### ISSUE TITLE
Unreal Engine 5.0.2 Path Tracer Not Working

### ISSUE THREAD

**Issue by KingKong19100** [eidosmontreal/unreal-vdb#27]
Hello, I'm trying to use this plug in with the Path Tracer for Unreal Engine 5.0.2, and for some reason this is not working. Is there any alternatives I can take? Can Explosions or Fire effects be converted to Volume Textures used in Sequencer? Please let me know and thank you so much!

**Comment by thilamb** [comment]
Is the path tracer not working at all or just the VDBs with path tracer ? I
recommend reading Unreal’s official documentation to activate the path
tracer.

Friendly reminder that only VdbPrincipledActors are compatible with the
path tracer.
https://github.com/eidosmontreal/unreal-vdb#the-hardcoded-way

You can convert them to Volume Textures indeed, but you will need to
implement your own Materials to handle both fire and explosions. Ryan
Bruck’s work is a good reference.

**Comment by KingKong19100** [comment]
> 

Hey thank you so much for the timely reply! Path Tracer itself is not working at all for me. I know there is not much you could do in that regard, so I'm trying to see what I could do in regards to what this plug in has to offer. That last option sounds excellent. I would love to convert my explosion asset to a Volume Texture (I believe that's what we're seeing with the tornado shown in the Documentation?), but implementing my own materials is a bit confusing to me. Would you be able to provide step by step directions as to how to do that? I appreciate the help so much, thank you sincerely!

**Comment by thilamb** [comment]
I'm sharing examples with the "data" package in release, if you want to check it out.
https://github.com/eidosmontreal/unreal-vdb/releases

It's definitely complex and will require more time, I'm afraid I can't help you more on that subject, sorry.
Maybe chekc this reference, https://shaderbits.com/blog/creating-volumetric-ray-marcher, or https://www.youtube.com/watch?v=NO1ZGbdE9ao&ab_channel=Dokipen.

Would love to sse your results if you're able to share them once you are ready though !
Good luck
