### ISSUE TITLE
Question regarding VDB

### ISSUE THREAD

**Issue by guitargodmiles** [eidosmontreal/unreal-vdb#28]
When using in Unreal Engine, is there a way a way to clip the vdb to make one side not render.

Ideally if there is X Y and Z depth, I would like to have an invisible plane that I can use to trim the Z depth so that part doesn't render.

My reason for requesting this is, I have a project where I have a large VDB that is partially through the ground floor.  I need to render a separate pass of the VDB on a transparent background but, when I disable all other objects visibility in the scene, the part under the ground then is shown which is not what I need.

Fingers crossed there is an easy workaround for this

**Comment by thilamb** [comment]
There is no way to clip a volume for now.

I`m not sure how you use a "separate pass", but you could also add that floor in the other pass, make it invisible but still writing in your depth buffer.

If you know how to code you could probably easily add your custom clipping in the shaders.

Good luck

**Comment by guitargodmiles** [comment]
Hello,  How do I make it invisible but, still write to my depth buffer?

I have tried changing the visibility of the floor object but, then I see
the smoke underneath.

Thanks
