### ISSUE TITLE
VDB to Niagara Fluid ...

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#3]
does a plan to deploy VDB plugin as base of the Niagara Fluid?
it would be great if VDB had a feature to use it as input of Niagara Fluid to get better rendering results :]

**Comment by thilamb** [comment]
I'm not sure what you exactly mean, but I've already added a limited VDB support in Niagara, as explained here:
https://github.com/eidosmontreal/unreal-vdb#niagara

I agree that having a better integration would be fantastic. That's something we are currently discussing with Epic, but don't expect anything soon (it could take a year).

I'm closing the issue as it is a bit vague and too generic, but feel free to open a new one or a feature request when you have a better idea of what you would want te be added. Thanks !
