### ISSUE TITLE
VDB sequence import doesn't work if the sequence starts on a frame other than 1

### ISSUE THREAD

**Issue by csvfx** [eidosmontreal/unreal-vdb#30]
I tried to import a sequence starting on 1001 and then another one starting on 500 (each sequence was in their own directory). The import window wouldn't recognise either sequence until I renamed them to all start at frame 001

**Comment by thilamb** [comment]
Thanks for reporting this. I'm looking into the issue and will keep you updated.

**Comment by thilamb** [comment]
I've pushed [the fix](https://github.com/eidosmontreal/unreal-vdb/commit/86529f85afc8514bdf9a19c7fe4856ec35f5acc2). 

It's already available if you use the code. If you use precompiled release version, I'll prepare a new one soon-ish (need to fix another issue first).

Thanks !
