### ISSUE TITLE
issue with Groom

### ISSUE THREAD

**Issue by nervYu** [eidosmontreal/unreal-vdb#32]
![aaa](https://user-images.githubusercontent.com/48727435/186166843-07019caa-3289-4462-a9e4-703fe85445ed.png)
when we put metahuman's groom and vdb object together the groom asset looks cut off from volume how can fix this?

**Comment by thilamb** [comment]
You can fix this particular issue by using a different render delegate.

Replace **RegisterPostOpaqueRenderDelegate** in [VdbMaterialRendering.cpp](https://github.com/eidosmontreal/unreal-vdb/blob/86529f85afc8514bdf9a19c7fe4856ec35f5acc2/Source/Runtime/Private/Rendering/VdbMaterialRendering.cpp#L250) by **RegisterOverlayRenderDelegate**.

You will have the inverse problem though, of hair in front of volume that might look odd. 

Let me know

**Comment by Andrej730** [comment]
@thilamb
Tested it - it actually does solve problem with groom being rendered through VDB but it does adds render artifacts on the edges of groom (compare ex 2 and 1). Anything to do about it?

Btw this solution does not affect volumetric or translucent materials in any way. 
Is there similar solution that would help with those types of materials also (#39)?


RegisterPostOpaqueRenderDelegate:
![PostOpaque groom](https://user-images.githubusercontent.com/9417531/197792585-a1d22c9d-1b64-4def-9495-6c96c4de144c.png)

RegisterOverlayRenderDelegate:
![Overlay groom](https://user-images.githubusercontent.com/9417531/197792600-21e6dd5a-e6eb-4294-83b4-4d51dda8d9aa.png)


Groom without vdb:
![Overlay groom bg](https://user-images.githubusercontent.com/9417531/197792614-082fe17b-04bb-4cc4-a4b5-0fd9abcc3199.png)

**Comment by Andrej730** [comment]
@thilamb can you please add the option to change the RenderDelegateHandle from actor's settings? 
It's just that when we have sorting issues sometimes it's better to use RegisterPostOpaqueRenderDelegate but sometimes the RegisterOverlayRenderDelegate is better. 
Currently the solution would be to have two different plugins for the different scenes...

And any ideas on:

> Btw this solution does not affect volumetric or translucent materials in any way.
> Is there similar solution that would help with those types of materials also (https://github.com/eidosmontreal/unreal-vdb/issues/39)?

**Comment by thilamb** [comment]
This is still a sensitive topic with lots of caveats. I don't see any viable solution coming until Epic releases their own solution and integrates VDBs in the regular translucency pipeline.

**Comment by thilamb** [comment]
I’ve added a console variable to control which delegate to use as asked. [Code update](https://github.com/eidosmontreal/unreal-vdb/commit/1947077882095d26a2b74b9ef9423e7e389bb4c3)
