### ISSUE TITLE
Rendering vdb with movie render queue cannot get the Alpha of vdb

### ISSUE THREAD

**Issue by ddShaShou** [eidosmontreal/unreal-vdb#33]
I use movei render queue to render vdb and I want to use object ids to get alpha of vdb. But unreal-vdb doesn't support it.

Then, I changed the method and used the layer method, but I still couldn't get the individual Alpha of the vdb.

**Comment by thilamb** [comment]
Hello, I'm not familiar with this object id method with the movie render queue (I'll take a look at it), but you can get the alpha and color of only your VDB volumes by using the "r.Vdb.DebugMode" option to display the composite (0), the smoke color only (1) or the smoke alpha only (2).

Let me know
