### ISSUE TITLE
Embergen Color to UE??

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#34]
hi,

how can i export **Color channel** that mentioned on image from **[EmberGen](https://jangafx.com/software/embergen/)**?
current version of EmberGen is **0.75**
thanks.

![Screenshot 2022-09-23 110124](https://user-images.githubusercontent.com/10723167/191912840-07644e1d-48a1-4103-9eb8-0ac074609cc1.png)

**Comment by thilamb** [comment]
I have no idea, you should ask the Embergen folks, they are responsive on
Discord.

Thanks
