### ISSUE TITLE
NeuralVDB support?

### ISSUE THREAD

**Issue by Frisbeetarian** [eidosmontreal/unreal-vdb#35]
First off thanks for this plugin! Amazing freaking work!
Any plans on supporting NeuralVDB?

**Comment by thilamb** [comment]
Thanks a lot !

NeuralVDB is not released yet (nor the specs) so it’s difficult to say if decompression will be fast enough to be used in realtime.

At worst, we will probably support it during import, but I personally hope that we will be able to use it on the fly and store 100x smaller data buffers. 

We’ll see !
