### ISSUE TITLE
Issue with Temperature VDB's & Color vectors 

### ISSUE THREAD

**Issue by Abroder8** [eidosmontreal/unreal-vdb#36]
Just wanted to say that this plugin is fantastic. I'm having a great time experimenting with it and exploring different ways it could be used in a cinematic workflow. 

I'm having one issue right now that I haven't been able to figure out. 

Simply put, when I try to drop a Temperature VDB or Color vector onto a newly created VdbPrincable actor nothing happens. It doesn't register. But I can see both temperature Vdb's and color vectors working when looking through your supplied example levels. The problem seems to occur whenever I try to add or even change one of these settings. This issue also happens when I use the example VDB's within these example levels, In an attempt to rule out possible import errors on my part. 

Any Ideas of where I might be going wrong? 

Many thanks for your help.

**Comment by thilamb** [comment]
Hello, and thanks a lot for the kind words ! I really appreciate it.

It sounds like you're not setting the mandatory **Density** volume. This is the only mandatory volume and the Vdb will not display if it is not set properly. 

_Temperature_ and _Color_ and both optional and supplementary volumes and are dependent on the first _Density_ volume (their properties/size have to match exactly).

Hope this helps ! Let me know

**Comment by thilamb** [comment]
Just wanted to share that I try to help users understand this (sometimes complex) plugin by adding a lot of tooltips on all variables. Make sure to read them if you feel lost 😊

**Comment by Abroder8** [comment]
Hello, thank you for the quick response :) 

Apologies for not explaining clearly enough, but I can confirm that in all my attempts the mandatory Density volume was already set. It is when trying to set either Temperature or colour (following on from density) I encounter the issue. 

I have attached a clip below to help show the issue. 

Thanks again for the help. 


https://user-images.githubusercontent.com/114530399/192880198-5ede260b-71c0-42e9-be98-82aeb15a5bd9.mp4

**Comment by thilamb** [comment]
I see, thanks for the video. This is a new check I added on secondary optional buffers. If they do not match the density buffer exactly (grids should have same size), I dismiss them. 

I do this for performance reasons, to avoid sampling N different grids at the same time and make the shader slower (that would require N times more shader instructions). 

That being said, maybe I'm a bit too restrictive, and I shouldn't do it. Let me take a look and I'll get back to you.

NB: if you're a programmer I can tell which lines to comment and you'll be good to go again

**Comment by thilamb** [comment]
Thanks a lot for reporting this issue. My recent additional check was indeed wrong and broke the last 0.6.0 update.

[I've fixed it in code](https://github.com/eidosmontreal/unreal-vdb/commit/2072b3681e7e493985f938ceb10c270584d87842#diff-483ca43e24477f07565081cc9e561f6898aa7c6b68c9fac7fd27fbf8d4d0cda2), and [have packaged a new precompiled version](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.1).

Apologies about the issue and please let me know if this new packaged update fixes your issue.

Thanks again, Cheers

**Comment by Abroder8** [comment]
Thank you for looking into it - Happy I was able to help by bringing it to your attention :) 

I will try the new version and let you know how it goes.

**Comment by ghost** [comment]
> Thank you for looking into it - Happy I was able to help by bringing it to your attention :)
> 
> I will try the new version and let you know how it goes.

when you convert houdini native volume to vdb it automaticly resize dimensions.
thanks for removing restriction.

**Comment by thilamb** [comment]
I'm not sure if this is a statement or a question ?

If it is an issue, can you please open another ticket with a more detailed description ? Thanks !
