### ISSUE TITLE
Light Interaction

### ISSUE THREAD

**Issue by lsohele** [eidosmontreal/unreal-vdb#37]
Hi. First, thank you so much for this plugin! I imported some VDB to test, and I noted that without a Direct Light, VDB is overbright. And I tried to interact with the volume imported using some colorful point lights and spotlights, but nothing happens. Is there a way to deal with that issues?
Thank you in advance.

**Comment by thilamb** [comment]
Hi, thanks for the kind words ! 

For now, the plugin only supports the first directional light and the skylight (environment light).

Sadly, there are no ways to access lighting and shadow information from a plugin.

You can use a Lit material shader or an Unlit one (use emissive field).

Hope this helps,
Cheers
