### ISSUE TITLE
Customizing VDB look

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#38]
1) I've tried to render with realitime render VBD with gasoline explosion from Emborgen and it's seems really pixelated. I've tried to tweak parameters and add more samples on render (tried 4 spatial and 64 temporal samples) but had no success. 
Any suggestions - how to make it look any better? 
Or is it matter of vdb detalization (this VBD is just 751 MB, maybe it's too small to look good)? Also tried to "Fire Plume" (5.5 GB), same pixelated result.

My result (the right one) - https://imgur.com/a/1QUuZBb
Reference from JangaFX - https://jangafx.com/downloads/VDB_CC0/gasoline_explosion_a_vdb.mp4

2) Is there any actor-type or something in Unreal that VDB in this plugin is based upon (like fog, clouds) or is it completely custom and it's using some hardcoded raymarching shader inside?

3) I've tried to render VDB to volume texture with VdbToVolumeTextureActor to get more control over resulting fog but resulting render texture is very low resolution (257x246x344) so it's quality cannot be compared to actual VDB. 
Is there way to change the resolution to something bigger to get more quality on the texture? 
I've tried to change it manually but every frame VdbToVolumeTextureActor seems to automatically change it's resoltion to the values below.

https://imgur.com/a/DevEcNL

4) Customizing emission color - by default vdb seems to be emitting plain white color. Is there way to change it - it would be help to blend vbd into scene more naturally (for example explosion would color scene in orange etc).

**Comment by thilamb** [comment]
Hello,

1. You can have trilinear sampling by using the "vdb trilinear" material available in the precompiled packages
It does look much better with it (especially with blackbodies) but it does cost a lot more.
![image](https://user-images.githubusercontent.com/7030046/194666270-87adb6d7-13b3-4966-ae2e-54f1f5336c2d.png)

2. Not really, I implement a completely custom Actor (inspired by VolumetricClouds) with some hardcoded raymarching inside indeed

3. Your texture will be exactly the same size as your VDB. Getting more "resolution" really depends on your rendering options and algorithm. You can get really nice results even with a small VDB when used appropriately. You're mentioning Fog so you're probably using Unreal's volumetric fog which is really low resolution itself. You can increase fog grid resolution with a few commands lines / console options.

4. You can change the emission color in the material itself. Just add a color/vector param on the material, and change it with your material instances.


Hope this helps and answers all your questions !

**Comment by Andrej730** [comment]
1. Thanks, it's much better looking with trilinear shader. 
I've done some tests and I think in most cases in real time render the must have settings are: 
\+ trilinear shader 
\+ jitter = 1 (especially important if there's some fire going on because it will fix obvious fire wave patterns) 
\+ `r.Vdb.Denoiser 1` (to smooth out the results of jitter) 
\+ render samples. 
I think it's important to mention those features in plugin description because after installing it's taking too much guessing and playing around to find these options exist.

2. About volumetric material - tried `r.VolumetricFog.GridPixelSize 1` and it worked, volumetric looks much more detailed now.

3. Regarding emission color - changing emission color is kind of works, it does changes color but it doesn't emit light on nearby objects. It looks like it does but I guess it's screen space bloom

https://user-images.githubusercontent.com/9417531/194714551-18191993-90d6-425a-b47a-27f66d7d7a3f.mp4

What I also noticed is that if you disable all lights in the scene VDB starts emitting very bright white light and it cannot be controled. Not sure if it's any important to fix though.
![UnrealEditor_Xgw4Mmax1i](https://user-images.githubusercontent.com/9417531/194710252-ffc48e98-03ed-4cfe-933f-01d108f8a762.png)


6. Any ideas how to blend VDB into the scene more seamlessly? Currently it's looking not bad but on the edges VDB looks more like it was integrated really rough, like it's flipbook or something.

https://user-images.githubusercontent.com/9417531/194710591-aee970e3-73f5-47c8-9acd-fc6bb7e0e421.mp4

**Comment by thilamb** [comment]
1. I plan on doing an updated documentation, and will try to make options simpler and clearer

2. Glad it works for you now

3. I can't integrate my VDBs in Lumen or any GI system sadly, so there's no color leaking. That's the expected behavior and the best I can do from a custom plugin. The white emissive is also expected behavior, it has to do with exposure levels. You will see the color if you had some strong bloom.

6. I think your issue is that it's not correctly blending with the transparent background. We'll follow up on your other issue.

I'll close this issue now as everything was "resolved", but feel free to re-open it or ask more info in other requests. Thanks !
