### ISSUE TITLE
VDB translucency sort priority problem

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#39]
I've met problems with translucency sort priority (really important issues because translucent materials are rendered incorrectly).

1) You can see translucent material clearly behind VDB (changing traslucent sort order doesn't work)
![VkzxG9M](https://user-images.githubusercontent.com/9417531/195094577-2a8450db-7259-416d-8d9c-fe5bbacfb6a3.png)
If VDB is behind translucent it's seems to looks fine.

2) You can see VDB clearly through Volume material (changing traslucent sort order doesn't work either).
![arOFmQg](https://user-images.githubusercontent.com/9417531/195097118-f77e0afe-d931-453f-be25-88b25aca0e9a.png)

**Comment by thilamb** [comment]
Hello, sadly I'm well aware of this issue and there's nothing I can do about it from a custom plugin.

I recommend not using translucent objects if possible. 

Sorry

**Comment by Andrej730** [comment]
I've found in UE5.1 Preview option to turn Ordered Independent Transparency - not sure how exactly it works but the premise is that translucency overlaying wouldn't use sorting order but would be actually calculated. Maybe it's possible to integrate it somehow to VDB too.

![ff1f116deaca065fa81ae1e1359f30624b9f9ec3](https://user-images.githubusercontent.com/9417531/195373466-6dc83d2c-654d-438b-a8d2-20ee99343f9b.png)

**Comment by thilamb** [comment]
Thanks ! I'll take a look

**Comment by Andrej730** [comment]
> Thanks ! I'll take a look

@thilamb any updates on Order Independent Transparency?

**Comment by Andrej730** [comment]
By the way, learned investigating Unreal volumetric clouds that's VDB is based upon that it has some way to do that sorting for volume material (examples in #48), even though issues with groom and translcucent materials still stay. 

Is there way to reproduce it in VDB to fix sorting with volume materials?

**Comment by thilamb** [comment]
OIT is not useable with my current system.

I'm trying to add VDB depth writing which helps in some cases but breaks in others, I'm not satisfied with the results yet so I can't share. Tried stochastic depth and translucency but it's not good enough.

In the gallery level you'll find an example of "regular" volume material sampling a VdbToVolumeTexture.
