### ISSUE TITLE
UE5 | 5.0.0 new compile needed 

### ISSUE THREAD

**Issue by dangerstudios** [eidosmontreal/unreal-vdb#4]
Hello,

Would it be possible to recompile for the latest UE5 released today?

Thanks

---------------------------
Missing xxx Modules
---------------------------
The following modules are missing or built with a different engine version:

  VolumeImporter
  VolumeSequencer
  VolumeStreamer
  VolumeRuntime

Would you like to rebuild them now?
---------------------------
Yes   No   
---------------------------

**Comment by prasetion** [comment]
ahh, same with me, how to use this plugin in UE5 released? it says need to recompile but somehow it should recompile from source(?), i dont know what it means, i still new in unreal

**Comment by thilamb** [comment]
I will do my best to compile it and release it today !
I will let you know as soon as it as done.
Thanks !

**Comment by thilamb** [comment]
I've uploaded the new version:
https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.3.0

Please tell me if it is working on your side before I close the issue. Thanks !

**Comment by dangerstudios** [comment]
seems to be working, thank you!!

![image](https://user-images.githubusercontent.com/63320852/162175521-373f51e3-0ddb-4a16-b2a5-7c26d75e0e7a.png)

**Comment by prasetion** [comment]
yeah, me too, it seems working. I already success import vdb sample bunny. Thanks dude

**Comment by thilamb** [comment]
Thank you both !
