### ISSUE TITLE
Viewport UV works incorrectly from VDB shaders

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#40]
I was looking for a workaround for #39 and my idea is to make some custom stencil based mask for volumetric materials and use it in VDB to reduce density - that way VDB wouldn't appear in front of volumes when it's actually is behind.

Example mask:

![HighresScreenshot00001](https://user-images.githubusercontent.com/9417531/195499326-074cfbfa-9c45-4b23-bbdd-3ceb7c94e385.png)

Then I was trying to sample it by viewport UV inside VDB shader:

![UnrealEditor_zjWb1mX0WA](https://user-images.githubusercontent.com/9417531/195499868-c3dd8db9-3c3a-4357-93ae-495042bf665e.png)

But the result looks like ViewportUV for the entire VDB is (0,0) and masking doesn't work:

![HighresScreenshot00003](https://user-images.githubusercontent.com/9417531/195499804-8c553a31-113e-4c91-ae11-2697fcfef352.png)

What I've also noticed is that if you try to get ViewportUV from vertex shader (using vertex interpolator) instead of pixel shader it's kind of works but UV seems to be distorted or shifted.

![UnrealEditor_ko0EegXGCS](https://user-images.githubusercontent.com/9417531/195500239-90a0c82b-8426-452b-9039-4f11aa124138.png)

![HighresScreenshot00002](https://user-images.githubusercontent.com/9417531/195500708-3b2be7a4-7fbe-4b8f-89fb-f70ee60bc4fd.png)

I've tested it with default unreal opaque and volume materials and it works fine there, so it's VDB specific issue.

![HighresScreenshot00004](https://user-images.githubusercontent.com/9417531/195500909-37f6f19e-5b7c-4b3b-a830-d38296323c8a.png)

Investigated shader code and it's seems like `Parameters.SvPosition` is always returning 0 and this is the reason why ViewportUV is always (0,0).

**Comment by thilamb** [comment]
Thanks a lot for showing me this issue. It is now fixed with this [commit](https://github.com/eidosmontreal/unreal-vdb/commit/d46b2a8f7ed823cc73e30932b24f0c5533fd1e13).

A precompiled version is available [here](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.2-5.1).

**Comment by Andrej730** [comment]
Tested new update - it works. Now I can make volumetric materials *kind of* translucent with the (a bit) cursed technique I described above 😁
Thank you.

![UnrealEditor_sEsO9nUKar](https://user-images.githubusercontent.com/9417531/197838175-4f635f67-a9a2-4883-9e78-f7a44e656d72.png)

**Comment by thilamb** [comment]
Nice, thanks for confirming !
