### ISSUE TITLE
Niagara Workflow

### ISSUE THREAD

**Issue by Himanshu9152704239** [eidosmontreal/unreal-vdb#41]
Please Share Some Kind Of examples for Niagara implementation in the project.
Add emitter template's\Levels For Explore the possibilities with Niagara.
Please Include it in the plugin contents.

Great Plugin

**Comment by thilamb** [comment]
Yes, I will when I can find some time ! I'll keep this issue open until then.
Thanks

**Comment by Himanshu9152704239** [comment]
Thanks for Reply 
I love YOur Work 
Thanks For Your Precious Time 
Love To See Some New Features 

Please Add Support For Shadow Cast on the world 

![HighresScreenshot00003](https://user-images.githubusercontent.com/15061409/199789074-7f8cded4-2ca6-4e2b-b7dc-39ec4807be72.png)
![HighresScreenshot00002](https://user-images.githubusercontent.com/15061409/199789366-1d02a6c5-73f1-4cdd-9a4b-2dafd162fdbd.png)

Here I Am using Embergen Unreal engine Scene File (https://www.youtube.com/watch?v=hCIObagoNNs)

The performance affected By Enabling Cloud Shadow is Too high.
