### ISSUE TITLE
VDB Writing to custom depth pass

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#43]
Is it possible to make vdb to write to custom depth pass but not as an entire actor's bounding box but as an actuall vdb effect?
It would help to better blend vdb with environmnent using postprocess materials (or translucent materials that can read custom stencil values too).

**Comment by thilamb** [comment]
Good question, I'll investigate.

**Comment by thilamb** [comment]
I took the time to check and sadly the code is not customizable from a plugin so I can't do this. Sorry.
