### ISSUE TITLE
Fog + Groom sorting

### ISSUE THREAD

**Issue by vfxbyjohn** [eidosmontreal/unreal-vdb#44]
Hey,

Just wondering if you or anyone else has ever tried to render groom with a fog volume? I'm currently trying todo just that and have noticed that the groom will always render in-front of the volume. I've tried using the console variable `r.HairStrands.ComposeAfterTranslucency 0` and while that works for materials like glass, it dosen't affect the vdb.
![fog_groom_01](https://user-images.githubusercontent.com/38900660/198904578-6a8ae0ec-970a-4915-8081-028f99a05fd1.jpg)

I'm assuming this is related to how the volume material is setup but I'm unsure if its something that can be solved?

This is using the VdbMaterialActor, if I switch to the VdbPrincipledActor it sorts correctly! But ideally I'd like to be able to use the Material Actor for game play :)

**Comment by Andrej730** [comment]
Same issue as #32

**Comment by thilamb** [comment]
Yes, sadly I'm aware of this issue and don't think there's a proper solution to the problem due to limited extensibility from a plugin, sorry.

**Comment by vfxbyjohn** [comment]
Ah thanks all, sorry I didn't see the previous post, I'll close out this one
