### ISSUE TITLE
openVDB points

### ISSUE THREAD

**Issue by wilsimar** [eidosmontreal/unreal-vdb#46]
Some plans to support openVDB points ? 
For particles simulations caches..
Openvdb points use far less memory that alembic point cloud
and unreal still can't read alembic point cloud.

[https://www.openvdb.org/documentation/doxygen/points.html](url)

**Comment by thilamb** [comment]
Houdini Niagara plugin supports point clouds and other plugins do too so I didn't bother supporting it myself.
https://www.sidefx.com/docs/unreal/_niagara.html#InitCache
https://github.com/sideeffects/HoudiniNiagara/releases

But there's probably a few advantages of using OpenVDB points ? Feel free to give me more info or references / links.

I could get convinced to do it, but it's going to be very low priority on my side sadly, I already don't have time to do what I need to do.
