### ISSUE TITLE
BP_VdbToVolumetricClouds

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#48]
Is there some description for BP_VdbToVolumetricClouds - how it works and how to set it up? 

Found it in the LVL_VDB_Sequencer that goes with SparseVolumetrics_ue5.1_0.6.2_with_data.
It's not mentioned anywhere but it seems like a great solution for #39 - it does look good on render and it has good sorting and it's blending well in the level! It seems like a good way to add some well blended vdb smokes in the scene.

And is there any way to add temperature to it or to fake it somehow?

![image](https://user-images.githubusercontent.com/9417531/204618189-3e1491e4-f5f8-4a99-af8f-f8d54432a32e.png)

**Comment by thilamb** [comment]
Hello,

There is no documentation on this blueprint but hopefully the provided exemple levels are self-explanatory.

This technique uses VDB to Volume texture, which can then be used anywhere you want in Unreal. I use with Unreal’s volumetric clouds (and also with some custom hlsl material in another level). Unreal volumetric clouds work great in general. But I’m not sure it’s going to solve all transparency issues (I don’t think it writes depth).

I wrote a very quick FAQ that helps you adding more clouds if you want:
https://github.com/eidosmontreal/unreal-vdb/blob/main/HELPME.md#faq


There is no way to add temperature though. You can try faking it in the material.

**Comment by Andrej730** [comment]
Have you met some example where someone managed to configure volumetric cloud + vdb to look good at really close distance? There is example that goes with plugin but the cloud-vdb is very far away and there is no need for the detail quality and sampling.

The main issue I have right it's still a bit noisy at the edges.
![image](https://user-images.githubusercontent.com/9417531/205123600-f41984b7-772b-4895-9a01-47952cf27c68.png)

**Comment by thilamb** [comment]
You would have to dabble with all the [console variables associated to volumetric clouds](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Renderer/Private/VolumetricCloudRendering.cpp#L35) to get your desired look.

The one I found that really helped a while ago was _r.VolumetricCloud.DistanceToSampleMaxCount_. There may be others.

**Comment by Andrej730** [comment]
> You would have to dabble with all the [console variables associated to volumetric clouds](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Renderer/Private/VolumetricCloudRendering.cpp#L35) to get your desired look.
> 
> The one I found that really helped a while ago was _r.VolumetricCloud.DistanceToSampleMaxCount_. There may be others.

Already tried all available settings.

**Comment by Andrej730** [comment]
Want to share some results investigating volumetric cloud

1) It does work better with volume materials (solves #39). Left cube is behind the VDB, right one is in front.
You can even see that Volumetric Scattering Intensity works too (I've left the gizmo for the point light with VSI).
![UnrealEditor_4caGld4Cir](https://user-images.githubusercontent.com/9417531/205214904-d9e3d9c6-6fe7-4544-8e26-c65eb97575fb.png)

2. Doesn't solve issues with translucent material - they are exactly the same as for VDB. Translucent in front looks fine, translucent behind has sorting issues and drawn over vdb.

![UnrealEditor_HU6KSUY5UG](https://user-images.githubusercontent.com/9417531/205215112-fe55358e-ce41-465a-b3ed-6f2a68b57cb2.png)

3. Groom has the same issues as translucent, the same way as it works in VDB (#32).
![image](https://user-images.githubusercontent.com/9417531/205216683-0f1d263b-16c8-4317-82c7-d51fbcd31039.png)

**Comment by thilamb** [comment]
Thanks for the update ! 

Are you showing three "clouds" in the first image ? Or are you mixing one volumetric cloud + 2 VdbMaterialActors ?

If it's the first case, it will work for sure as it should also work with 3 VdbMaterialActors (they are sorted from camera distance).

I'm not surprised with points 2. and 3. . I've even taken more time to investigate hair strands, and also noticed they have the same issue with transparent objects behind. They do write depth which helps sometimes but breaks some other times. I have a local branch trying to fix this but I'm not happy with the results yet. I've tried stochastic transparency and stochastic depth but TAA doesn't converge towards a good solution enough.

**Comment by Andrej730** [comment]
>Are you showing three "clouds" in the first image ? Or are you mixing one volumetric cloud + 2 VdbMaterialActors ?

The cloud is volumetric cloud that's using volume texture from VDB. 
Cubes are static meshes with volume material.

**Comment by Andrej730** [comment]
I think I've found a solution for translucent materials (thanks to advice from Asher Zhu).

The solution is to use "Apply Cloud Fogging" is the settings of translucent material.

![image](https://user-images.githubusercontent.com/9417531/206889799-10a54eda-eaf4-4a3c-9027-daff00e58932.png)


Without fogging:

![UnrealEditor_Y8OCaFizeK](https://user-images.githubusercontent.com/9417531/206889826-f8d5e512-40e4-4e0e-a13c-8e4299ed09b0.png)


With fogging:
![UnrealEditor_bZGrGOkryI](https://user-images.githubusercontent.com/9417531/206889829-9806eed3-e955-456a-8664-bb6e5f616dfb.png)

So the only current problem with VDB clouds (besides not having temperature) is sorting with groom sorting.
Also tried to use `r.HairStrands.ComposeAfterTranslucency 0/1/2/3` to fix the groom problem but it didn't worked.

**Comment by thilamb** [comment]
Excellent, thanks for sharing the solution !
