### ISSUE TITLE
Houdini Axiom to Unreal-VDB tutorial??

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#50]
hey,
does exists any tutorial to describe how to make vdb for Unreal-VDB with [**Axiom**](https://www.theoryaccelerated.com/)?

thanks.

**Comment by thilamb** [comment]
No there isn’t but like any other digital content creator it should be able to export your sims to VDB files (you can probably find some Axiom tutorials). 

Once exported, juste import them in Unreal using advices from [README.md](https://github.com/eidosmontreal/unreal-vdb#first-steps)  and from here [HELPME.com](https://github.com/eidosmontreal/unreal-vdb/blob/main/HELPME.md#basic-instructions) as well.

**Comment by davoodkharmanzar** [comment]
also i tried to import ...
but did not showed up anything :[

![1](https://user-images.githubusercontent.com/10723167/206764077-1046b5a6-9525-416d-a9fb-216752e282fb.jpg)

![2](https://user-images.githubusercontent.com/10723167/206764102-23365935-2518-46cf-a9a5-ff5f87a7a48a.jpg)

![3](https://user-images.githubusercontent.com/10723167/206764118-1094e8c1-489b-48f7-a986-c9ffaa60f9b3.jpg)

**Comment by davoodkharmanzar** [comment]
any suggestions?
thanks.

**Comment by thilamb** [comment]
Try increasing « Density » (100, 500, 1000?) and decreasing « (Local) Step
size » (1, 0.1, 0.01) until you see something. Let me know.

**Comment by davoodkharmanzar** [comment]
nice ...
yup ... it worked ...

but ...

1) have to 100 times scale up on unreal ... any suggestions?

2) i have facing problem with Color Channel (aka **Cd** on Houdini) ... sometimes plugin can read this and sometimes doesn't accept it!! why??

P.S.: used **pyrobakevolume** node to adjust channels on houdini ...

**Comment by thilamb** [comment]
1. The 100 times scale up is normal. Every software use different distance units. Unreal uses centimeters (1 unit == 1 cm). I don't know about Houdini and I guess it's customizable, in the editor and also maybe during export.

2. I'm not sure about this one. The "color" vdb should have the same transform (and basic properties) as the main "density" vdb. And it should have values between 0 and 1. If you find a specific issue, let's open another ticket with a better report and repro case (sharing the vdbs would be ideal). 

Thanks !
