### ISSUE TITLE
BUG - Clouds from BP_VdbToVolumetricClouds are invisible on level reopen

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#51]
I think I've found a small bug - after you reopen the level with BP_VdbToVolumetricClouds clouds become invisible. The way to fix it is to tweak some cloud component parameter (like "Layer Heigh"), clouds will show and then you can revert tweaked valeus.

Video:

https://user-images.githubusercontent.com/9417531/206889282-1df73a2f-e8e0-4209-bdbf-f90f5b275f2e.mp4

Example level (requires SparseVolumetrics with "embergen_gasoline_explosion_a_seq_density" installed):
[Cloud VDB bug example map.zip](https://github.com/eidosmontreal/unreal-vdb/files/10201574/Cloud.VDB.bug.example.map.zip)

**Comment by thilamb** [comment]
Thanks for the report. I'm not really working on the plugin any more so I can't guarantee a fix any time soon, but I'll try if I can.

**Comment by thilamb** [comment]
Sorry but I don't have the energy to look into this. Best, Thibault.
