### ISSUE TITLE
Reading Color Channel Bug ...

### ISSUE THREAD

**Issue by davoodkharmanzar** [eidosmontreal/unreal-vdb#52]
hey,
seems that the **color channel** reader or nano converter have bug ...
just got success to reading on single frame ...
on sequential import, the plugin was failed to accept it ...

**UE 5.1 + plugin [v0.6.2-5.1.0](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.2-5.1.0)**

here is an vdb example that created with Houdini + Axiom ...

**single frame VDB:**
[Single.zip](https://github.com/eidosmontreal/unreal-vdb/files/10202641/Single.zip)

**sequential VDB:**
[Sequential.zip](https://github.com/eidosmontreal/unreal-vdb/files/10202648/Sequential.zip)

**Comment by thilamb** [comment]
Thanks a lot, this really helped. 

The code is now fixed with [this update](https://github.com/eidosmontreal/unreal-vdb/commit/882d74c9474f2dcfde79f76ad2def7109ec44cbc).

If you can afford waiting a bit longer I'll prepare a release a bit later with some other fixes ? If not I can do it asap.

**Comment by davoodkharmanzar** [comment]
yup ...

i'll be waiting for the next release for UE 5.1 ...
and hope to see **alpha render pass** as well  :P

thanks.

**Comment by davoodkharmanzar** [comment]
hey,
another thing that would be great to be fixed is **Debug Mode 2** [alpha pass] should be rendered after post process ...
i mean currently postprocess was affected on alpha results of vdbs and it does not good!?

**Comment by thilamb** [comment]
True, post processing should be disabled when using these debug modes. I might have an idea to implement your post-processing option. I'll get back to you when it's working.

**Comment by thilamb** [comment]
I managed to add this feature. Available in the next release :).

![Vdb_AOVs](https://user-images.githubusercontent.com/7030046/210803687-49e47dd3-8159-46a4-aba3-c7c576d822a7.png)

**Comment by thilamb** [comment]
Available in the [latest release](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.3_ue5.1.0)

Thanks for your feedback ! I hope you will like it.
