### ISSUE TITLE
VDB static clouds can't decide who is where

### ISSUE THREAD

**Issue by flat4er** [eidosmontreal/unreal-vdb#54]
![image](https://user-images.githubusercontent.com/5252598/207589297-e88ad5ae-d944-4d85-bfc4-1c1a8dcab165.png)
![image](https://user-images.githubusercontent.com/5252598/207589351-03a79b2e-2a78-4853-a81b-661789f6945b.png)

**Comment by thilamb** [comment]
VDBs are sorted back to front, depending on camera position. You will have issues with overlapping VDBs for sure, it is a classic realtime problem and you would get the same results with overlapping windows for example.

I recommend merging overlapping VDBs, or using Unreal's Volumetric Cloud system which only support a single "cloud" to resolve that kind of issues.
