### ISSUE TITLE
Compiling shader stuck UE Version: 5.0.3-20979098+++UE5+Release-5.0

### ISSUE THREAD

**Issue by Haytham9181** [eidosmontreal/unreal-vdb#56]
After turning on the plugin and restarting the project compile shaders stuck, can't open the project

**Comment by thilamb** [comment]
Is this still bothering you ? 

Can you please try the[ latest release](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.3_ue5.1.0) ? I've removed some heavy shader variations.

**Comment by Haytham9181** [comment]
It takes some time like 1 hour maybe but the Project is loaded. Thanx anyway
