### ISSUE TITLE
Issue with building from Visual Studio and deployment

### ISSUE THREAD

**Issue by jacquesvaneeden** [eidosmontreal/unreal-vdb#57]
Hi

This is a great plugin, thanks for the effort!!

Deploying the project from Unreal doesn't work once I have the plugin installed, also building from Visual studio fails after adding the plugin to the project. 

Here is the deployment error dump

LogClass: Error: StructProperty FVdbRay::Origin is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogClass: Error: StructProperty FVdbRay::Direction is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogClass: Error: FloatProperty FVdbLevelSetHit::t is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogClass: Error: FloatProperty FVdbLevelSetHit::v0 is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogClass: Error: IntProperty FVdbLevelSetHit::i is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogClass: Error: IntProperty FVdbLevelSetHit::j is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogClass: Error: IntProperty FVdbLevelSetHit::k is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogAutomationTest: Error: UObject.Class AttemptToFindUninitializedScriptStructMembers will be marked as failing due to errors being logged
LogAutomationTest: Error: LogClass: StructProperty FVdbRay::Origin is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogAutomationTest: Error: LogClass: StructProperty FVdbRay::Direction is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogAutomationTest: Error: LogClass: FloatProperty FVdbLevelSetHit::t is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogAutomationTest: Error: LogClass: FloatProperty FVdbLevelSetHit::v0 is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogAutomationTest: Error: LogClass: IntProperty FVdbLevelSetHit::i is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogAutomationTest: Error: LogClass: IntProperty FVdbLevelSetHit::j is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h
LogAutomationTest: Error: LogClass: IntProperty FVdbLevelSetHit::k is not initialized properly. Module:VolumeRuntime File:Private/Niagara/NiagaraDataInterfaceVdb.h

**Comment by thilamb** [comment]
Thanks ! I think you should remove your warning-as-error compilation
setting. I don’t think it’s activated by default so I’m guessing you
enabled it for your project. This can be set on a per module basis.

I’m in-between jobs right now and need a new computer setup so it’s
difficult for me to fix these warnings quickly. But I’ll let you know as
soon as I take care of it.

**Comment by jacquesvaneeden** [comment]
Thibault

I don't have warnings as errors enabled, unless there is something new in Unreal 5.1

I can build the solution but launching from VS gives me this 

1>Expecting to find a type to be declared in a module rules named 'VolumeImporter' in UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.  This type must derive from the 'ModuleRules' type defined by Unreal Build Tool.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command ""D:\Epic\Epic Games\UE_5.1\Engine\Build\BatchFiles\Build.bat" MyProject2Editor Win64 Development -Project="D:\Epic\MyProjects\MyProject2\MyProject2.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "MyProject2.vcxproj" -- FAILED.

**Comment by jacquesvaneeden** [comment]
We are doing digital twinning of bulk material handling systems, thus far I have been using Nvidia GVDB for visualization, you plugin opened a completely new door using Unreal.  
Apart from getting everything stable and running I have a couple of additional items on my wish list, might also need a little input from your side on using your plugin in c++ for a couple of advanced things we need to do 

I can give you access to a remote, already setup, system if it will help

**Comment by thilamb** [comment]
We fixed this issue with Jacques directly. I'm sharing the solution in case it helps others.

He was not using full Unreal C++ sources, just the minimum headers files from the official installer. And he put the VDB plugin in the engine source plugins folder, which didn't work.

Putting the VDB plugin in the project folders (like I usually recommend to do) fixed the issue.

Thanks Jacques, feel free to reach out again if needed.
