### ISSUE TITLE
5.1 Plugin Crash

### ISSUE THREAD

**Issue by Dragonroad3D** [eidosmontreal/unreal-vdb#59]
Hi~Unreal 5.1 Plugin Crash!
[UECC-Windows-330E6D09465DE7442C8ECA8587AE172D_0000.zip](https://github.com/eidosmontreal/unreal-vdb/files/10443039/UECC-Windows-330E6D09465DE7442C8ECA8587AE172D_0000.zip)

**Comment by thilamb** [comment]
I think this is fixed now. Can you please update to the latest Release and confirm ?
