### ISSUE TITLE
Animating - path tracing 

### ISSUE THREAD

**Issue by nathanmelaku** [eidosmontreal/unreal-vdb#6]
First I must say this plugin is a dream come true.
Didn't understood the process of animating in path tracing. Can u make a tutorial ?

**Comment by thilamb** [comment]
Thanks a lot for your kind words ! We really appreciate it.

You are not the only asking for such a tutorial, so I made a detailed one [here](https://github.com/eidosmontreal/unreal-vdb/blob/main/TutorialSequencer.md):
https://github.com/eidosmontreal/unreal-vdb/blob/main/TutorialSequencer.md

Hopefully you will like it and be able to test your own animations.

Have fun
