### ISSUE TITLE
Intersecting temperature(flame) won't render/show

### ISSUE THREAD

**Issue by cnnhean** [eidosmontreal/unreal-vdb#65]
If you import using the latest version, the intersecting flame isn't showing. 
-So if i use the same vdb sequance for density and temperature no color shows at all. 
Vdb sequances that was imported using previous versions seems still be working as before, while newly imported vdb's would have this problem. 

Btw this is such an amazing work you've done, the plugin is so good!

**Comment by thilamb** [comment]
This looks like a data problem. Can you at least share one VDB frame ? And show comparisons before / after ?

**Comment by cnnhean** [comment]
Yes, just a moment

**Comment by cnnhean** [comment]
I made the wrong assumption. 
I think my problem was that "black body temperature" was just set too low due to the slider limit

![image](https://user-images.githubusercontent.com/27144745/221250484-d8d86a9d-eb91-4587-a49c-8c3856d7c66a.png)

![image](https://user-images.githubusercontent.com/27144745/221250797-48d6a723-14cf-4b75-badc-6357a78051e6.png)

**Comment by thilamb** [comment]
Ok, glad you could sort that out ! And thanks for the compliments 😊.

Take care
