### ISSUE TITLE
Additional platforms

### ISSUE THREAD

**Issue by nicnodal** [eidosmontreal/unreal-vdb#66]
Hi! This plugin is incredibly powerful, thank you for your hard work on it. Do you have plans to develop support for other platforms? PS5/XBOX? How difficult would it be, if feasible at all?

**Comment by thilamb** [comment]
Thanks a lot ! 

I do not plan on supporting consoles but I'm pretty sure it would "just work" if you tried (with maybe some minor modifications). The code is console and API agnostic, you just need a performant GPU.

Hope this helps, let me know if you make it work.
