### ISSUE TITLE
VDB Fps

### ISSUE THREAD

**Issue by mszawdyn** [eidosmontreal/unreal-vdb#67]
Hi, I'm so exited to use this VDB plugin, thank you. 
I use UE5 5.1 and latest VDB UE5.1.1_0.6.5 plugin 

My issue is I don't get all of the vdb sequence frames in my UE5 sequencer. 

I exported 200 frames with 25 fps from Houdini
when importing UE5 shows 200 on status bar
in sequencer I have only 166 frames

I've tried to export 50 frames from Houdini,
in sequencer I get 41

my FPS in Houdini and UE5 sequencer is both 25fps
changing frame range in VDB sequence properties in sequencer doesn't change it.

Please help, this drains my motivation ;/

**Comment by thilamb** [comment]
Hello, the plugin forces VDB import at 30fps.

If your sequence if at 25fps, that means 25/30 * 200 frames = 166 frames (and 25/30 * 50 frames = 41 frames).

Just change the "Playback / Playback speed" to get your preferred fps, knowing that we import everything at 30fps. This is on top of modifying sequencer fps (if you want to).

**Comment by mszawdyn** [comment]
Thanks for your help! Got confused with this fps:)

**Comment by thilamb** [comment]
No worries, have fun !
