### ISSUE TITLE
Combining BP_VdbToVolumetricClouds with default unreal clouds

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#69]
How can I combine default unreal engine volumetric clouds and the clouds produced with BP_VdbToVolumetricClouds?

**Comment by thilamb** [comment]
Unreal uses a unified cloud system, meaning you can only have one active in the scene.

The magic is happening in the material. Just copy/paste and combine the regular unreal cloud material with the provided BP_VdbToVolumetricClouds and it will work.
