### ISSUE TITLE
Blackbody Shader

### ISSUE THREAD

**Issue by dangerstudios** [eidosmontreal/unreal-vdb#7]
Hello,

How would I go about creating one based on the materials provided?

Cheers!

**Comment by thilamb** [comment]
Hi, I recently added a tutorial showing how to do a blackbody shader:
https://github.com/eidosmontreal/unreal-vdb/blob/main/TutorialSequencer.md

It is currently only possible with the second rendering mode (VdbResearchActor)

**Comment by dangerstudios** [comment]
ah cool! does it have to be path-traced to work?

**Comment by thilamb** [comment]
No it doesn’t, but it’s clearly going to be super noisy. The shader was tailored for path-tracing. I recommend tweaking the shader yourself to get better results in realtime, if you know how.

Have fun !
