### ISSUE TITLE
Can´t import vdb files

### ISSUE THREAD

**Issue by MichaKaka** [eidosmontreal/unreal-vdb#70]
i dont know what i did wrong, but i tried everything now. Installed the newest release into the ue5.1.1 plugins folder, activated the plugin n a new project, but if I drag a vdb file in the content browser, a message pops up that says that the file could not be imported 

Message: Failed to import 'G:\Unreal Engine Projects\Neyroo_Tüv_camp3\Cloud Stuff\CloudPack\CloudPackVDB\cloud_03_variant_0000.vdb'. Failed to create asset '/Game/cloud_03_variant_0000'.
Please see Output Log for details.

Output Log:
LogFactory: FactoryCreateFile: VdbVolumeStatic with VdbImportFactory (0 0 G:\Unreal Engine Projects\Neyroo_Tüv_camp3\Cloud Stuff\CloudPack\CloudPackVDB\cloud_03_variant_0000.vdb)
LogVdbFiles: Error: Could not read VDB file G:\Unreal Engine Projects\Neyroo_Tüv_camp3\Cloud Stuff\CloudPack\CloudPackVDB\cloud_03_variant_0000.vdb:
IoError: could not get size of file G:\Unreal Engine Projects\Neyroo_Tￃﾼv_camp3\Cloud Stuff\CloudPack\CloudPackVDB\cloud_03_variant_0000.vdb
LogSlate: Window 'Message' being destroyed
Message dialog closed, result: Cancel, title: Message, text: Failed to import 'G:\Unreal Engine Projects\Neyroo_Tüv_camp3\Cloud Stuff\CloudPack\CloudPackVDB\cloud_03_variant_0000.vdb'. Failed to create asset '/Game/cloud_03_variant_0000'.
Please see Output Log for details.
LogAssetTools: Warning: Failed to import 'G:\Unreal Engine Projects\Neyroo_Tüv_camp3\Cloud Stuff\CloudPack\CloudPackVDB\cloud_03_variant_0000.vdb'. Failed to create asset '/Game/cloud_03_variant_0000'.
Please see Output Log for details.

**Comment by MichaKaka** [comment]
btw: I can open the example levels in the editor and the volumes work just fine there, I just can´t import anything.

**Comment by thilamb** [comment]
That's a message from OpenVDB library not being able to open the vdb file.

I'm guessing you've tried with other VDB files as well ? Do you have a conflicting OpenVDB version on your computer ? One that you compiled yourself or something like this ?

**Comment by kmac5** [comment]
I believe the problem is being caused by the non-ascii character "ü" in the folder named "Neyroo_Tüv_camp3".  I tested with that folder name on my system and saw the same error when loading a known good vdb, then renamed the folder to "Neyroo_Tuv_camp3" and the vdb loaded.

**Comment by thilamb** [comment]
Nice, you can post an issue on the openvdb github if you want, but I'm glad to know you were able to fix it manually.

**Comment by MichaKaka** [comment]
> I believe the problem is being caused by the non-ascii character "ü" in the folder named "Neyroo_Tüv_camp3". I tested with that folder name on my system and saw the same error when loading a known good vdb, then renamed the folder to "Neyroo_Tuv_camp3" and the vdb loaded.

Damn thank you! I have seen something with he letter ü in the Output log but didn´t know what to d with that immediately. But that makes sense now.
