### ISSUE TITLE
Plugin Not Installing properly

### ISSUE THREAD

**Issue by stevojames** [eidosmontreal/unreal-vdb#72]
Hi there!
I've been trying to install this plugin but Unreal won't open due to this error that keeps popping up. I thought I had followed the instructions for proper installation and you can see the file path at the top in case I did it wrong.

Thanks for the help!
![Screenshot 2023-04-04 093158](https://user-images.githubusercontent.com/129873901/229827471-97dbd22e-f44f-4010-a682-45a81ceaa5e9.png)

**Comment by thilamb** [comment]
I'm not sure what is happening but when this message usually pops up, it shows all 4 modules missing, not just one.

Are you sure the .zip file is entirely downloaded or not corrupted ?

**Comment by thilamb** [comment]
Any update on this issue ? What version of Unreal are you using ? Thanks
