### ISSUE TITLE
Error when loading a level with VDBs

### ISSUE THREAD

**Issue by BBI-BrandonMartin** [eidosmontreal/unreal-vdb#73]
I can put VDBs into a level and even render out of sequencer, but when I save and attempt to load the level again, I get this:
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff
UnrealEditor_VolumeRuntime!FVdbMaterialRendering::Render_RenderThread() [D:\Dev\UE_Proj\Packages\SparseVolumetrics_ue_5.1.1_0.6.6\SparseVolumetrics\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbMaterialRendering.cpp:497]
UnrealEditor_VolumeRuntime!TBaseRawMethodDelegateInstance<0,FVdbMaterialRendering,void __cdecl(FPostOpaqueRenderParameters &),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [D:\Dev\UE_5.1\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:475]

**Comment by thilamb** [comment]
Hello, do you still have this issue everytime ?

**Comment by BBI-BrandonMartin** [comment]
Yeah, I just added them back into the level and got the same error. 

I'm trying to replicate it in a second level with no luck so far. It seems fine with sky lights, sky atmo, hdri backdrop, exp height fog, so I'm not sure what else to try. Would it have a problem with water shaders or metahuman hair, perhaps?

**Comment by BBI-BrandonMartin** [comment]
I added a hair groom, a lake and an ocean into the second level and it still doesn't crash...

**Comment by thilamb** [comment]
Thanks a lot for the update. Strange indeed. 
If you do have a crash again please copy paste the callstack so that I can check if it is the same, or if it can give me more info.

It really helps everyone if we can fix this issue so thanks again for helping me debug this particular case.

**Comment by BBI-BrandonMartin** [comment]
Is there a specific section that you're looking for? I need to make sure I don't send anything sensative.

**Comment by BBI-BrandonMartin** [comment]
<FGenericCrashContext>
	<RuntimeProperties>
		<CrashVersion>3</CrashVersion>
		<ExecutionGuid>60C80F6D41FB59A90842B8B0D6371D55</ExecutionGuid>
		<CrashGUID>UECC-Windows-21DC33DF447FDA2D38DC5980090A4F7B_0001</CrashGUID>
		<IsEnsure>false</IsEnsure>
		<IsStall>false</IsStall>
		<IsAssert>false</IsAssert>
		<CrashType>Crash</CrashType>
		<ErrorMessage>Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff</ErrorMessage>
		<CrashReporterMessage />
		<ProcessId>7172</ProcessId>
		<SecondsSinceStart>70</SecondsSinceStart>
		<IsInternalBuild>false</IsInternalBuild>
		<IsPerforceBuild>false</IsPerforceBuild>
		<IsSourceDistribution>false</IsSourceDistribution>
		<GameName>UE-Raven_Cine</GameName>
		<ExecutableName>UnrealEditor</ExecutableName>
		<BuildConfiguration>Development</BuildConfiguration>
		<GameSessionID />
		<PlatformName>WindowsEditor</PlatformName>
		<PlatformNameIni>Windows</PlatformNameIni>
		<EngineMode>Editor</EngineMode>
		<EngineModeEx>Dirty</EngineModeEx>
		<DeploymentName />
		<EngineVersion>5.1.1-23901901+++UE5+Release-5.1</EngineVersion>
		<CommandLine>[redacted file location]</CommandLine>
		<LanguageLCID>0</LanguageLCID>
		<AppDefaultLocale>en-US</AppDefaultLocale>
		<BuildVersion>++UE5+Release-5.1-CL-23901901</BuildVersion>
		<Symbols>**UE5*Release-5.1-CL-23901901-Win64-Development</Symbols>
		<IsUERelease>true</IsUERelease>
		<IsRequestingExit>false</IsRequestingExit>
		<UserName />
		<BaseDir>C:/Program Files/Epic Games/UE_5.1/Engine/Binaries/Win64/</BaseDir>
		<RootDir>C:/Program Files/Epic Games/UE_5.1/</RootDir>
		<MachineId>D21223B84162332C4ECD898AF3520262</MachineId>
		<LoginId>d21223b84162332c4ecd898af3520262</LoginId>
		<EpicAccountId>e238d9af0b1e4d8490b345eef417df70</EpicAccountId>
		<SourceContext />
		<UserDescription />
		<UserActivityHint>Layout=&quot;LevelEditorViewport&quot; Label=&quot;Viewport 1&quot; Content=SAssetE</UserActivityHint>
		<CrashDumpMode>0</CrashDumpMode>
		<GameStateName />
		<Misc.NumberOfCores>14</Misc.NumberOfCores>
		<Misc.NumberOfCoresIncludingHyperthreads>28</Misc.NumberOfCoresIncludingHyperthreads>
		<Misc.Is64bitOperatingSystem>1</Misc.Is64bitOperatingSystem>
		<Misc.CPUVendor>GenuineIntel</Misc.CPUVendor>
		<Misc.CPUBrand>Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz</Misc.CPUBrand>
		<Misc.PrimaryGPUBrand>NVIDIA GeForce RTX 4090</Misc.PrimaryGPUBrand>
		<Misc.OSVersionMajor>Windows 10 (21H2) [10.0.19044.2728]</Misc.OSVersionMajor>
		<Misc.OSVersionMinor />
		<MemoryStats.TotalPhysical>68412751872</MemoryStats.TotalPhysical>
		<MemoryStats.TotalVirtual>78613299200</MemoryStats.TotalVirtual>
		<MemoryStats.PageSize>4096</MemoryStats.PageSize>
		<MemoryStats.TotalPhysicalGB>64</MemoryStats.TotalPhysicalGB>
		<MemoryStats.AvailablePhysical>50779504640</MemoryStats.AvailablePhysical>
		<MemoryStats.AvailableVirtual>51883024384</MemoryStats.AvailableVirtual>
		<MemoryStats.UsedPhysical>8747163648</MemoryStats.UsedPhysical>
		<MemoryStats.PeakUsedPhysical>8747167744</MemoryStats.PeakUsedPhysical>
		<MemoryStats.UsedVirtual>14234488832</MemoryStats.UsedVirtual>
		<MemoryStats.PeakUsedVirtual>14234488832</MemoryStats.PeakUsedVirtual>
		<MemoryStats.bIsOOM>0</MemoryStats.bIsOOM>
		<MemoryStats.OOMAllocationSize>0</MemoryStats.OOMAllocationSize>
		<MemoryStats.OOMAllocationAlignment>0</MemoryStats.OOMAllocationAlignment>
		<NumMinidumpFramesToIgnore>0</NumMinidumpFramesToIgnore>
		<CallStack>UnrealEditor_VolumeRuntime!FVdbMaterialRendering::Render_RenderThread() [D:\Dev\UE_Proj\Packages\SparseVolumetrics_ue_5.1.1_0.6.6\SparseVolumetrics\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\Rendering\VdbMaterialRendering.cpp:497]
UnrealEditor_VolumeRuntime!TBaseRawMethodDelegateInstance&lt;0,FVdbMaterialRendering,void __cdecl(FPostOpaqueRenderParameters &amp;),FDefaultDelegateUserPolicy&gt;::ExecuteIfSafe() [D:\Dev\UE_5.1\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:475]
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Renderer
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_RenderCore
UnrealEditor_RenderCore
UnrealEditor_Core
UnrealEditor_Core
kernel32
ntdll</CallStack>

**Comment by BBI-BrandonMartin** [comment]
Let me know if you want any of the PCallStack or PCallStackHash

**Comment by thilamb** [comment]
Hello, I'm really sorry I couldn't find more time to work on this. 

The callstack is not really helpful unfortunately. Have you tried the 5.2 version by any chance ? If yes, have you noted any difference ?

**Comment by BBI-BrandonMartin** [comment]
Hey, no worries. We're on 5.1.1 until the Nuke plugin gets updated.

**Comment by thilamb** [comment]
Hi, I pushed a new version that I think will fix this issue.

https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.9_ue5.1.1

Let me know ! Thanks.

**Comment by BBI-BrandonMartin** [comment]
Excelent, I'll take a look
