### ISSUE TITLE
The plugin is incompatible with Unreal 5.2

### ISSUE THREAD

**Issue by ethan-tqa** [eidosmontreal/unreal-vdb#75]
Hi, just want to raise this issue for awareness. Something changed in Niagara in Unreal 5.2 (preview 2), that makes this plugin fail to compile.

**Comment by thilamb** [comment]
Ok thanks a lot I will take a look.

**Comment by samrat333** [comment]
we tried to built many time but failed to Niagara issue

**Comment by renanmgs** [comment]
Yes please, we that do  cinematics gonne be happy!

**Comment by thilamb** [comment]
I'm just waiting for the official and final 5.2 version to come out to update and release the plugin. Hopefully very soon !

**Comment by samrat333** [comment]
> I'm just waiting for the official and final 5.2 version to come out to update and release the plugin. Hopefully very soon !

what is problem with build if success update source code please

**Comment by thilamb** [comment]
https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.7_ue5.2.0

**Comment by samrat333** [comment]
final release 5.2 your source code is not build and plugin not working in 5.2
