### ISSUE TITLE
Lit/Pathtracing

### ISSUE THREAD

**Issue by mszawdyn** [eidosmontreal/unreal-vdb#76]
Hi,

I can see my cloud vdb only in lit mode, it disappears when changing to pathtracing. Any solution for this?
Also in lit mode vdbs seems a bit grainy and act weirdly when panning a cam.
![image](https://user-images.githubusercontent.com/127866296/231754257-b87b6919-13dd-4456-b9fa-680b8dae1630.png)

**Comment by thilamb** [comment]
Hello, only _VdbPrincipledActors_ are compatible with pathtracer.

See [this doc](https://github.com/eidosmontreal/unreal-vdb#using-the-sequencer-and-the-movie-render-queue) and [this one](https://github.com/eidosmontreal/unreal-vdb/blob/main/TutorialSequencer.md).
