### ISSUE TITLE
Speed/Frame Count issue after export

### ISSUE THREAD

**Issue by PoodlePunter** [eidosmontreal/unreal-vdb#77]
Hi, I'm having an issue with my frame count and speed inside of Unreal.
Inside of the Volume Frames Info section in the Properties of my NanoVDBSequence it says the correct number of frames (380), but when I import it into my level and into my sequencer it only shows there being 304 frames and they are going faster than I need them to. 
I tried adjusting the playback speed but it doesn't seem to be doing anything.
Is this a known issue? Really hope to get this fixed, I've spent months working on this project and getting the Smoke from Houdini into Unreal was very tough to figure out until I found this plugin, but now I still can't get it to work.
Any help would be greatly appreciated.

**Comment by thilamb** [comment]
Hello, the plugin imports sequences at 30fps. I'm guessing you exported at 24fps.

"Playback speed" is indeed the right parameter that you should change to make it work (so probably value of 24/30 = 0.8) and so far there's been no issue with it (and I know a lot of people like you use it). You can edit this parameter on the VDB actor itself, or directly in the Sequencer.

Let me know.

**Comment by PoodlePunter** [comment]
Thanks for the help, how do I add the playback speed to the sequencer? I didn't see a way to add it or to keyframe it in the properties panel.

**Comment by thilamb** [comment]
Right click on the sequence and open "Properties"

![image](https://user-images.githubusercontent.com/7030046/232153396-97c25e86-95c4-41b0-bb84-2d6111533b21.png)
