### ISSUE TITLE
Volume not rendering when camera is inside of it.

### ISSUE THREAD

**Issue by PoodlePunter** [eidosmontreal/unreal-vdb#78]
Hi all, I'm sorry if this isn't the right place for this, just curious if there is a way to get the volume to show up when my camera is inside it?
I noticed It disappears in the viewport when I'm inside of it and tried a render with my camera inside of it and it's not showing up.
My camera is inside of the smoke pretty much the whole time and I kind of need the volume to render even when it is.
Thanks for any assistance.

**Comment by thilamb** [comment]
Hello, it should not disappear.

People have reported some edge cases that I fixed but you might have another one. Can you share a single frame of your VDB sequence please ? This will help me solve the issue. It can be private if you want / need.

**Comment by PoodlePunter** [comment]
Yes of course, it won't let me share a vdb file on here though, how should I send it?

**Comment by PoodlePunter** [comment]
Here is a Google Drive link, I hope that is okay.
https://drive.google.com/file/d/1w69fDXMah4W_pRconSKoF5QkoNTOXzkL/view?usp=sharing

**Comment by thilamb** [comment]
Thank you ! Your VDB has in internal negative scaling, which is supported with the plugin from [0.6.6](https://github.com/eidosmontreal/unreal-vdb/releases/tag/v0.6.6_ue5.1.1).

Which plugin version are you using ?

**Comment by PoodlePunter** [comment]
Im pretty sure I'm using 0.6.6. I will double check though.

**Comment by PoodlePunter** [comment]
I did run into an issue when I first imported it with it seemingly mirrored so I reversed the scale and changed the rotations how I wanted it to make it display properly. I'm now assuming this is because of the negative scaling you are talking about, could this change I've done to it be part of the problem.

**Comment by PoodlePunter** [comment]
I just checked and I actually have 0.6.5, I don't know why I didn't update the most recent one. I will install the new version today and reimport everything and let you know how it goes, thank you!

**Comment by PoodlePunter** [comment]
Thank you so much! That fixed it! 
Sorry for my Unreal Noob questions, but I really appreciate you taking the time to help me out.
Great work on the plugin btw.

**Comment by thilamb** [comment]
Happy to help ! Thanks for the kind words. Good luck with your project (would love to see it when finalized).
