### ISSUE TITLE
Fire as light source

### ISSUE THREAD

**Issue by xXchrizzoXx** [eidosmontreal/unreal-vdb#83]
Hey thilamb,

thank you very much for the plug-in! It also works with houdini <3
A vdb sequence with fire for example doesn't emit light on its own so that it illuminates its surroundings, right? - Or am I doing something wrong?

Greetings,
Chrizzo

**Comment by Andrej730** [comment]
@xXchrizzoXx hi! Had similar question in #38
Not sure if it's not emitting any light at all but I remember that it doesn't emit color.
There is hope here that it *might* work at point in the future - https://github.com/EpicGames/UnrealEngine/pull/10344

BUT in this plugin there is BP_VdbToVolumetricClouds that can help you render your VDB to Volume Texture and then you can render this texture with unreal Volumetric Clouds as a cloud. Volumetric Clouds are already integrated in Unreal so there may be some opportunity to make them glow with Temperature/Flames VDB pass in the Volumetric Cloud shader (I've described related process here - https://github.com/eidosmontreal/unreal-vdb/issues/81#issuecomment-1541505732)

![image](https://github.com/eidosmontreal/unreal-vdb/assets/9417531/c6aaf838-c453-4479-bc52-99536ec0d78c)
![image](https://github.com/eidosmontreal/unreal-vdb/assets/9417531/2d1bed43-1ea6-4c33-b77c-8f929c9bf03d)

**Comment by thilamb** [comment]
Hi Chrizzo, thanks for the kind words !

I'm not currently doing anything special to make Fire illuminate the rest of the environment but I recently noticed that the Lumen GI probes do capture the emissive Fire emission, [cf my Twitter post here](https://twitter.com/LambertTibo/status/1657793646412853249).

It's probably going to be subtle in a fully illuminated scene but it worked in my little experiment.

FYI this won't work with the Pathtracer though, because it doesn't use Lumen.

Cheers

**Comment by xXchrizzoXx** [comment]
Thank you guys very much for the quick and comprehensive answers! <3

Okay, I will look more into why it's not working on my end. My scene is pretty dark, but maybe the fire is to small to emit enough light:
![image](https://github.com/eidosmontreal/unreal-vdb/assets/73641044/2bc4a8d9-bd96-43cd-9677-ff4a3b3ea25e)


Cheers Andrey730 and thilamb

**Comment by thilamb** [comment]
Lumen needs large sources of emissive to take them into account indeed ! The larger the better but of course it's not always possible. Good luck with this, would be happy to see your results if you can make it work.

**Comment by xXchrizzoXx** [comment]
Thank you!
Sure, it's a personal project so no NDA or something :D

**Comment by xXchrizzoXx** [comment]
Update, it seams to be a lumen issue. In the next days I try to make a gif which shows it.
