### ISSUE TITLE
Importing VDB sequence frame rate

### ISSUE THREAD

**Issue by zmardini** [eidosmontreal/unreal-vdb#84]
I cached a 24FPS vdb sequence, and imported it into unreal.

When i add the vdb sequence to a level sequence at 30FPS, everything is fine, but when i change the level sequence framerate to 24fps, the vdb sequence would still be at 30FPS, i would have to slow down the playback rate by roughly 0.8 in order for it to play the frames correctly.

is there any solution to this ?

**Comment by thilamb** [comment]
Hello, you are absolutely right and you should use an exact 0.8 "play rate" in the sequencer to make it match the 24fps. (24/30 = 0.8)

I will eventually allow users to change the VDB sequence play rate but for now it is fixed to 30fps. It's on my TODO list.

https://github.com/eidosmontreal/unreal-vdb/blob/main/HELPME.md#i-exported-my-vdb-sequence-at-24fps-but-it-looks-like-the-plugin-is-forcing-30fps-can-i-fix-that-
