### ISSUE TITLE
The following modules are missing or built with a different engine version

### ISSUE THREAD

**Issue by jkerman2000** [eidosmontreal/unreal-vdb#85]
My project is purely visual and has no source code, so I cannot "compile" it. I copy the folder from the releases page to my project's plugin folder and it doesn't start. It just gives me the message "the following modules are missing or built with a different engine version" even though I'm running 5.2. This is URGENT, as my college final depends on it.

**Comment by thilamb** [comment]
[Install guide](https://github.com/eidosmontreal/unreal-vdb#regular-users).

**Comment by jkerman2000** [comment]
> [Install guide](https://github.com/eidosmontreal/unreal-vdb#regular-users).

So I did all that, and when I click "rebuild" it returns the message "could not build, try rebuilding the project from source."

**Comment by thilamb** [comment]
Are you sure the have the right plugin version with the right Unreal version ?

5.2 or 5.1.1, not 5.1 etc.. https://github.com/eidosmontreal/unreal-vdb/releases
