### ISSUE TITLE
VDBs not rendering in Depth pass

### ISSUE THREAD

**Issue by xXchrizzoXx** [eidosmontreal/unreal-vdb#87]
Is it possible to make the volumes of the vdb render in the scene depth? Otherwise I have problems with the depth of field. The depth of field of the objects behind the volume gets applied to the volume. Normally you can enable the option "Output Velocity" in translucent materials, but that doesn't work for me.

Attached are images, that should show the problem.
Beauty Pass:
![HighresScreenshot00024](https://github.com/eidosmontreal/unreal-vdb/assets/73641044/bb8882d2-7c01-4109-a477-a05c38c1a2a2)

Albedo Pass:
![HighresScreenshot00025](https://github.com/eidosmontreal/unreal-vdb/assets/73641044/e93462b0-3f4e-4b33-b3eb-437e4b2c01fd)

Scene Depth:
![HighresScreenshot00026](https://github.com/eidosmontreal/unreal-vdb/assets/73641044/132d227b-4378-41fb-a338-d03c577fde24)

As a workaround I've placed a plane with a dither pattern right behind the fire, but this introduces artifacts in the final rendering.

**Comment by thilamb** [comment]
Hello, there's no way to write to depth with the current versions of the plugin but I do have a future branch that does it. I'm just waiting for a few stars to align to release the new updated plugin. No ETA for now I'm afraid, sorry.
