### ISSUE TITLE
getting weird artifact 

### ISSUE THREAD

**Issue by digitalguerrero** [eidosmontreal/unreal-vdb#89]
Hello, I am getting a streak looking artifact coming from the side off all vdb I load in. They shrink and grow from different angles when I tumble around the volume. I am applying my Volume Ray March material to a cube. Other than this they look great! I did notice in the volume texture that the last couple textures are reading "Bad Size". I couldn't find a way to fix the bad size image and not sure if they are related. Any help on solving this would be appreciated! 

![Capture](https://github.com/eidosmontreal/unreal-vdb/assets/130382416/fcd7eb97-3e68-4a3a-8401-0d54d2a23757)
![Capture_02](https://github.com/eidosmontreal/unreal-vdb/assets/130382416/b86d5f05-bb50-4786-b53f-2d06198e9656)
![Capture_03](https://github.com/eidosmontreal/unreal-vdb/assets/130382416/48dfa643-cfa6-4b82-97a3-68d5d50cf42f)

**Comment by thilamb** [comment]
Hi, this is an issue related to how you sample the **border** of your volume texture.

You might be able to change your texture settings to account for that.
![image](https://github.com/eidosmontreal/unreal-vdb/assets/7030046/c78c5ea5-a391-4e97-b749-faae68e50ff9)


If not, you should change your raymarch material to sample 0 (black) on volume borders so that they don't extend like this in your viewport.

**Comment by digitalguerrero** [comment]
Great thanks that worked, changing to a power of 2 removed the bad images and no more streaks! One more question though, my VDB got smaller in resolution and lost details and now have a lot of empty black images in the array. I can get my details back by increasing the steps to compensate but is there a better solution? 

![Capture](https://github.com/eidosmontreal/unreal-vdb/assets/130382416/5bff9aea-09d0-4983-84bf-673a1534329b)

**Comment by thilamb** [comment]
That sounds alright. Padding the texture just increased the overall resolution but didn't change the active data that was already there. Increasing step or re-adjusting active volume bounds will help.
