### ISSUE TITLE
Hello im using EmberGen and i would like to use the plugin to insert VDB files into unreal

### ISSUE THREAD

**Issue by lexazB** [eidosmontreal/unreal-vdb#9]
Hello im trying to find a way to get my Embergen simulation into Unreal Engine, i found your plugin but i cant seem to make it work, could you help me to complete the installation

1- I create a new UE5 project
2- I close that project and go to the project file location
3- In there i Created a folder Called "Plugins"
4-Copy the repo _.zip_ file and extracted the files in there

5- Error Missing Modules:   The following modules are missing or built with a diferrent engine version: VolumeImporter VolumeSequencer VolumeStreamer VolumeRuntime would you like to rebuild them now?

6- I click yes
7- Could not be compiled. Try rebuilding from source manually.

What im doing wrong?
![vdberror](https://user-images.githubusercontent.com/103798090/163657506-bdf7f2f9-ae60-40d8-b5a4-6b8e8945da72.PNG)

**Comment by thilamb** [comment]
Are you using the .zip from the Release folder (precompiled files) ?
https://github.com/eidosmontreal/unreal-vdb/releases

All your other steps seem fine.

**Comment by lexazB** [comment]
> Are you using the .zip from the Release folder (precompiled files) ? https://github.com/eidosmontreal/unreal-vdb/releases
> 
> All your other steps seem fine.

That seem to work just fine, im sorry for the newby question, i want to also thank you for develpoing this tool, i havent found any other similar method for getting VDB files into unreal, its a great contribution to the VFX community. i will start experimenting now wish me luck. Thanks again. also i loved the guardians of the galaxy game you and your team developed.

**Comment by thilamb** [comment]
No worries, and thanks a lot for the kind words, I’ll make sure to relay your message to the team. Enjoy !
