### ISSUE TITLE
Sparse Volume Textures

### ISSUE THREAD

**Issue by Andrej730** [eidosmontreal/unreal-vdb#90]
Epic Games announced support for sparse volume textures in 5.3. 
Could BP_VdbToVolumetricClouds benefit from it, if clouds will be using SVT instead of VT to sample the volume data? 
Any benefits of using SVT for VdbMaterialActor/VdbPrincipledActor instead of current VDB assets?

Probably too early to talk about but any plans on implementing support for SVT or it will be out of scope for the project?
Epic Games announced special SVT renderer for path tracing but no such thing for real-time so supporting it might come in handy

https://portal.productboard.com/epicgames/1-unreal-engine-public-roadmap/c/1171-sparse-volume-textures-experimental

**Comment by thilamb** [comment]
Hello,

> Could BP_VdbToVolumetricClouds benefit from it, if clouds will be using SVT instead of VT to sample the volume data?

Absolutely

> Any benefits of using SVT for VdbMaterialActor/VdbPrincipledActor instead of current VDB assets?

SVT should be faster to sample, so faster to render.

> Probably too early to talk about but any plans on implementing support for SVT or it will be out of scope for the project?

Probably not. SVT, it wouldn't change much except maybe for a little performance gain.

> Epic Games announced special SVT renderer for path tracing but no such thing for real-time so supporting it might come in handy

Yes this is very cool, Epic's path-tracer is not customizable from a plugin so it's nice that they're the integration themselves
