### ISSUE TITLE
"Assertion Failed" When attempting to render sequence UE 5.2.1 

### ISSUE THREAD

**Issue by REEEV3S** [eidosmontreal/unreal-vdb#92]
![image](https://github.com/eidosmontreal/unreal-vdb/assets/70071363/970efa5b-ce7f-479e-891c-475160b8b250)

Not sure whats triggering this or how I can start to debug it. Im on UE 5.2.1 and using the latest sparse volumetric, will provide more info if necessary. 

"Assertion failed: IndexLastChunk < VdbSequence->GetNbFrames() [File:D:\Dev\UE_Projects\SparseVolumetricsBuilds\SparseVolumetrics\HostProject\Plugins\SparseVolumetrics\Source\Runtime\Private\VdbSequenceComponent.cpp] [Line: 312]"

![image](https://github.com/eidosmontreal/unreal-vdb/assets/70071363/785028d1-9268-4027-bb63-f74ad252d41d)

**Comment by thilamb** [comment]
Thanks, I would love to know more about your scene. 

Would you be able to share your project privately , ideally the lightest version of it ?

**Comment by REEEV3S** [comment]
if anyone else gets this issue uncheck "looping" on your vdb, thank you so much thilamb for the incredibly simple solution

**Comment by thilamb** [comment]
To be more precise, a VDB grid was invalid at a certain frame, causing the import to skip the frame and create a disparity between VDB grids.

[I pushed a fix to cancel import when detecting invalid data](https://github.com/eidosmontreal/unreal-vdb/commit/5d14745a0adae0be1a5c46351dd732a1bb7aac88). Invalid VDB sequences will not crash in editor anymore.

Thanks for reporting the issue !
